mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: gvb_db
  user: root
  password: yanjun
  log_level: dev
  max_idle_conns: 10
  max_open_conns: 100
  max_conn_lifetime: 14400
logger:
  level: info
  prefix: '[GVB]'
  director: log
  show_line: true
  log_in_console: true
  path: ./log/myLog.log
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2008-03-15 06:17:34"
  record: ""
  title: 连什今圆强则头
  qq_image: http://dummyimage.com/400x400
  version: dolore ullamco commodo consequat
  email: v.rridn@qq.com
  wechat_image: http://dummyimage.com/400x400
  name: 色国育六重
  job: ""
  addr: anim
  slogan: ""
  slogan_en: incididunt fugiat velit sit
  web: ""
  bilibili_url: http://xsiyb.gy/qfkucp
  gitee_url: http://nuufhd.ug/vmbt
  github_url: http://grmwdqvenl.cl/syyopu
qq:
  app_id: xxx
  key: xxx
  redirect: http://blog.fengfengzhidao.com/login?flag=qq
qi_niu:
  enable: true
  access_key: xxx
  secret_key: xxx
  bucket: xxx
  cdn: xxx
  zone: z2
  prefix: fengfeng
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: 2974771769@qq.com
  password: xxx
  default_from_email: 枫枫知道
  use_ssl: true
  user_tls: false
jwt:
  secret: xxxx
  expires: 20
  issuer: "1234"