mysql:
  host: 
  port: 
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: 
  user: 
  password: 
  log_level: dev
  max_idle_conns: 10
  max_open_conns: 100
  max_conn_lifetime: 14400
logger:
  level: 
  prefix: 
  director: 
  show_line: 
  log_in_console: 
  path: ./log/myLog.log
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site_info:
  created_at: 
  record: ""
  title: ""
  qq_image: ""
  version: ""
  email: ""
  wechat_image: ""
  name: ""
  job: ""
  addr: ""
  slogan: ""
  slogan_en: ""
  web: ""
  bilibili_url: ""
  gitee_url: ""
  github_url: ""
email:
  host: 
  port: 
  user: 
  password: 
  default_from_email: 
  use_ssl:
  user_tls: 
jwt:
  secret: 
  expires: 
  issuer: 
qi_niu:
  enable: 
  access_key: 
  secret_key: 
  bucket: 
  cdn: ""
  zone: 
  prefix: 
  size: 5
qq:
  app_id: 
  key: ""
  redirect: ""
upload:
  size: 2
  path: uploads/file
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
  db: 0
