mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user: root
  password: yanjun
  max_idle_conns: 10
  max_open_conns: 100 # 最大空闲连接数
  max_conn_lifetime: 14400 # 最多可容纳
  log_level: dev # 连接最大复用时间 小于等于mysql的wait_timeout
  

logger:
  level: info
  prefix: '[GVB]'
  director: log #目录
  show_line: true
  log_in_console: true
  path: "./log/myLog.log"

system:
  host: "0.0.0.0"
  port: 8080
  env: release # release debug check
  