mysql:
    host: 127.0.0.1
    port: 3306
    config: "charset=utf8mb4&parseTime=True&loc=Local"
    db: gvb_db
    user: root
    password: yanjun
    log_level: dev
    max_idle_conns: 10
    max_open_conns: 100
    max_conn_lifetime: 14400
logger:
    level: info
    prefix: '[GVB]'
    director: log
    show_line: true
    log_in_console: true
    path: ./log/myLog.log
system:
    host: 0.0.0.0
    port: 8080
    env: release
site_info:
    created_at: "2013-07-05 19:56:27"
    record: minim Lorem incididunt
    title: 导了口往严它
    qq_image: http://dummyimage.com/400x400
    version: ""
    email: q.naps@qq.com
    wechat_image: http://dummyimage.com/400x400
    name: 想得水需
    job: ""
    addr: laborum ut nisi
    slogan: Duis
    slogan_en: ""
    web: ""
    bilibili_url: http://ecowyhis.sn/tykpjhlysq
    gitee_url: http://krguikn.ua/bswsvwwb
    github_url: http://ntjhgxyfko.tel/fbblfdgii
email:
    host: ipsum sunt Excepteur ullamco culpa
    port: 21
    user: sed nostrud exercitation ut
    password: reprehenderit deserunt
    default_from_email: b.khanstuo@qq.com
    use_ssl: false
    user_tls: false
jwt:
    secret: sint enim
    expires: 69
    issuer: tempor incididunt aliqua
qi_niu:
    enable: true
    access_key: ""
    secret_key: ""
    bucket: Excepteur
    cdn: ipsum
    zone: laborum minim
    prefix: Excepteur veniam ea nulla voluptate
    size: 96
qq:
    app_id: "34"
    key: qui ea irure in
    redirect: voluptate in magna aliqua
upload:
  size: 2
  path: uploads/file