mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: yanjun
  log_level: dev
  max_idle_conns: 10
  max_open_conns: 100
  max_conn_lifetime: 14400
logger:
  level: info
  prefix: '[GVB]'
  director: log
  show_line: true
  log_in_console: true
  path: ./log/myLog.log
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site_info:
  created_at: "2013-07-05 19:56:27"
  record:
  title:
  qq_image:
  version: ""
  email:
  wechat_image:
  name:
  job: ""
  addr:
  slogan:
  slogan_en: ""
  web: ""
  bilibili_url:
  gitee_url:
  github_url:
email:
  host: ""
  port: 21
  user: xxx
  password: ""
  default_from_email: b.khanstuo@qq.com
  use_ssl: false
  user_tls: false
jwt:
  secret: "zyuuforyu"
  expires: 720
  issuer: "zyuu"

# 七牛云 图片设置
qi_niu:
  enable: false
  access_key: "ERpQ2dJ8acGpjWjxb1N4IouEENpBhxInCcYs6lZP"
  secret_key: "qU70P6PiUhSAZ9VylMyALPWG1nIqta327XypaqV-"
  bucket: "zyuuoverseas"
  cdn:
  zone: as0
  #华南-广东  z2
  #华东      z0
  #华东-浙江  cn-east-2
  #华北      z1
  #南美洲    na0
  #新加坡    as0
  #东北      ap-northeast-1
  prefix: gvb
  size: 5
qq:
  app_id: "34"
  key: ""
  redirect: ""
upload:
  size: 2
  path: uploads/file
redis:
  ip: 127.0.0.1
  port: 6379
  password:
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: 
  